oe_authentication.settings:
  type: config_object
  label: 'OpenEuropa Authentication settings'
  mapping:
    protocol:
      type: string
      label: 'Application authentication protocol'
    register_path:
      type: string
      label: 'Application register path'
    validation_path:
      type: string
      label: 'Application validation path'
    assurance_level:
      type: string
      label: 'Application assurance levels'
    ticket_types:
      type: string
      label: 'Application available ticket types'
    redirect_user_register_route:
      type: boolean
      label: 'Redirect Drupal user registration route to EU Login'
